# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          public class Main {
  
          public static void main(String[] args) {

        // Definindo o nome e a quantidade de XP do herói
        String nomeHeroi = "Herói Exemplo";
        int xpHeroi = 7000; // Exemplo de XP, você pode ajustar conforme necessário

        // Utilizando uma estrutura de decisão para determinar o nível
        String nivel;
        if (xpHeroi < 1000) {
            nivel = "Ferro";
        } else if (xpHeroi >= 1001 && xpHeroi <= 2000) {
            nivel = "Bronze";
        } else if (xpHeroi >= 2001 && xpHeroi <= 5000) {
            nivel = "Prata";
        } else if (xpHeroi >= 6001 && xpHeroi <= 7000) {
            nivel = "Ouro";
        } else if (xpHeroi >= 7001 && xpHeroi <= 8000) {
            nivel = "Platina";
        } else if (xpHeroi >= 8001 && xpHeroi <= 9000) {
            nivel = "Ascendente";
        } else if (xpHeroi >= 9001 && xpHeroi <= 10000) {
            nivel = "Imortal";
        } else {
            nivel = "Radiante";
        }

        // Exibindo a mensagem final
        System.out.println("O herói de nome " + nomeHeroi + " está no nível de " + nivel);
    }
}
